# Generated by Django 5.2 on 2025-05-08 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaigndonation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='campaigndonation',
            unique_together=set(),
        ),
    ]
